name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       description: "Image version"
  #       required: true

#2
env:
  REGISTRY: "registry.digitalocean.com/gl-demo"
  SERVER_NAME: "wf"
  CLIENT_NAME: "cli"
  #IMAGE_TAG: "$(echo $GITHUB_SHA | head -c7)"

#3
jobs:
  build_and_push_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build container image
        run: |
          cd server
          docker build -t $(echo $REGISTRY)/$(echo $SERVER_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Remove all old images
        run: if [ ! -z "$(doctl registry repository list | grep "$(echo $SERVER_NAME)")" ]; then doctl registry repository delete-manifest $(echo $SERVER_NAME) $(doctl registry repository list-tags $(echo $SERVER_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $SERVER_NAME):$(echo $GITHUB_SHA | head -c7)

  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x]

  #   steps:
  #     - name: Checkout the repo
  #       uses: actions/checkout@v3

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"

  #     - run: |
  #         cd client
  #         npm ci

  #     - run: |
  #         cd client
  #         npm run build --if-present

  #     - run: |
  #         cd client
  #         npm test

  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          cd client
          npm install
      # build and test the apps
      - name: build
        run: |
          cd client
          npm run build
          # npm test

  push_to_Docker_Hub:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # build docker image and push to docker hub
    # only if the app build and test successfully
    needs: [build_test]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build container image
        run: |
          cd client
          docker build -t $(echo $REGISTRY)/$(echo $CLIENT_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Remove all old images
        run: if [ ! -z "$(doctl registry repository list | grep "$(echo $CLIENT_NAME)")" ]; then doctl registry repository delete-manifest $(echo $CLIENT_NAME) $(doctl registry repository list-tags $(echo $CLIENT_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $CLIENT_NAME):$(echo $GITHUB_SHA | head -c7)

  deploy:
    runs-on: ubuntu-latest
    needs: [push_to_Docker_Hub]

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: SERVER_NAME,REGISTRY,{{ secrets.DIGITAL_OCEAN_TOKEN }},GITHUB_SHA
          script: |
            # Login to registry
            docker login -u ${{ secrets.DIGITAL_OCEAN_TOKEN }} -p ${{ secrets.DIGITAL_OCEAN_TOKEN }} registry.digitalocean.com
            # Stop running container
            docker stop $(echo $SERVER_NAME)
            docker stop $(echo $CLIENT_NAME)
            # Remove old container
            docker rm $(echo $SERVER_NAME)
            docker rm $(echo $CLIENT_NAME)
            # Run a new container from a new image
            docker run -d \
            --restart always \
            --name $(echo $SERVER_NAME) \
            -p 8080:8080 \
            $(echo $REGISTRY)/$(echo $SERVER_NAME):$(echo $GITHUB_SHA | head -c7)
            # Run another container
            docker run -d \
            --restart always \
            --name $(echo $CLIENT_NAME) \
            -p 3000:3000 \
            $(echo $REGISTRY)/$(echo $CLIENT_NAME):$(echo $GITHUB_SHA | head -c7)
