name: Go

# trigger when user push the branches
on:
  push:
    branches: [ main ]

# jobs that are triggered with the push action above
jobs:

  build:
    runs-on: ubuntu-lasted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...


  - deploy:
    needs: build
    